homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 100
  unit_system: imperial
  time_zone: !secret time_zone
  name: Home

default_config:

influxdb:
  host: !secret influxdb_ip

zwave: !include config/zwave.yaml

automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include_dir_merge_list config/sensors/

light:
  - platform: group
    name: All Lights
    entities:
      - light.bedroom_area
      - light.bedroom_overhead
      - light.living_room_overhead

zoneminder:
  host: !secret zmhost
  path: /zm/
  ssl: true
  verify_ssl: false
  username: zmusername
  password: zmpassword

camera:
  - platform: zoneminder
