homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 100
  unit_system: imperial
  time_zone: !secret time_zone
  name: Home

default_config:

zwave: !include config/zwave.yaml
weather: !include config/weather.yaml
input_boolean: !include config/inputBoolean.yaml
input_datetime: !include config/inputDatetime.yaml

automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include_dir_list config/sensors/

light:
  - platform: group
    name: All Lights
    entities:
      - light.bedroom_area
      - light.bedroom_overhead
      - light.living_room_overhead

