title: 'Overview'
path: 'overview'
cards:
  - type: glance
    entities:
      - entity: script.bedtime
        name: Bedtime
        icon: mdi:hotel
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.bedtime
  - type: light
    entity: light.living_room_overhead
  - title: Living room
    type: entities
    show_header_toggle: true
    entities:
      - light.living_room_overhead
  - title: Morning lights
    type: entities
    show_header_toggle: false
    entities:
      - input_datetime.wakeup_time
      - input_boolean.wakeup_enabled
      - input_boolean.wakeup_weekend
  - title: Bedroom
    type: entities
    show_header_toggle: true
    entities:
      - light.bedroom_overhead
      - light.bedroom_area
  - type: weather-forecast
    entity: weather.dark_sky
