title: System
path: system
cards:
  - type: horizontal-stack
    cards:
      - type: sensor
        name: 'CPU Usage'
        entity: sensor.processor_use
        graph: line
        detail: 2
      - type: sensor
        name: 'RAM Usage'
        entity: sensor.memory_use_percent
        graph: line
        detail: 2
  - type: entities
    name: Last Boot
    entities:
      - sensor.last_boot
    format: date
