- alias: 'Set theme at startup'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: default
- alias: 'Toggle light'
  trigger:
    - platform: state
      entity_id: switch.living_room_1
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_all_lights
- alias: "Wake me up with bedroom light transition for weekdays"
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.wakeup_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
      - condition: state
        entity_id: input_boolean.wakeup_enabled
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekend
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
  action:
    - service: light.turn_on
      entity_id: light.bedroom_area
      data:
        transition: 1000
        brightness: 100
